meaningfull message to end-user
instead of repeating almost word-for-word the diagnostic error from ykcs11 lib (which is show right above this line btw), show something that have *any* meaning to the end user, who likely do not know what a "reader" is.

Before:
```
$ yubico-piv-tool --verbose -a status
error: no usable reader found.
Failed to connect to reader.
```

after
```
$ yubico-piv-tool --verbose -a status
error: no usable reader found.
Failed to connect to yubikey.
Have you tried turning it off and on again
```

The last line is, obviously, helpful but extraneous, mostly to make a point that i am not a contributor here and someone who knows the end users better than i do should write the actual new text :)